package com.example.grammarengpro.utils

object Const {
    const val DIRECT_VERIFY = "DIRECT_VERIFY"
    const val DIRECT_DETAIL_GRAMMAR = "DIRECT_DETAIL_GRAMMAR"
    const val DIRECT_DETAIL_PRACTICE = "DIRECT_DETAIL_PRACTICE"

    const val KEY_GRAMMAR = "BUNDLE_GRAMMAR"
    const val KEY_QUESTION = "KEY_QUESTION"
    const val KEY_POSITION_QUESTION = "KEY_POSITION_QUESTION"
    const val KEY_ID_PRACTICE = "KEY_ID_PRACTICE"
    const val KEY_POINT_PRACTICE = "KEY_POINT_PRACTICE"

    const val PREFS_LIST_POINT_PRACTICE = "PREFS_LIST_POINT_PRACTICE"
    const val PREFS_LIST_TIME_CHOOSE = "PREFS_LIST_TIME_CHOOSE"
    const val PREFS_OPEN_NOTIFICATION = "PREFS_OPEN_NOTIFICATION"
    const val PREFS_TIME_CHOOSE = "PREFS_TIME_CHOOSE"
    const val PREFS_CHECK_ALARM = "PREFS_CHECK_ALARM"

    const val ACTION_SWIPE_QUESTION = "ACTION_SWIPE_QUESTION"
    const val ACTION_SET_EXACT_ALARM = "ACTION_SET_EXACT_ALARM"
    const val ACTION_SET_REPETITIVE_ALARM = "ACTION_SET_REPETITIVE_ALARM"

    const val REQUEST_PRACTICE = 10

    const val ALARM_RECEIVER_ACTION = "ALARM_RECEIVER_ACTION"

    const val REQUEST_CODE = 99
    const val EXTRA_EXACT_ALARM_TIME = "EXTRA_EXACT_ALARM_TIME"
    const val EXTRA_REPETITIVE_ALARM = "EXTRA_REPETITIVE_ALARM"
}